const ASSETS=[
  ["bitcoin","BTC","Bitcoin"],["ethereum","ETH","Ethereum"],["tether","USDT","Tether"],["binancecoin","BNB","BNB"],
  ["ripple","XRP","XRP"],["usd-coin","USDC","USD Coin"],["solana","SOL","Solana"],["tron","TRX","TRON"],
  ["hyperliquid","HYPE","Hyperliquid"],["dogecoin","DOGE","Dogecoin"]
];
const FALLBACK={bitcoin:90000,ethereum:3800,tether:.85,binancecoin:720,ripple:2.4,"usd-coin":.85,solana:180,tron:.30,hyperliquid:35,dogecoin:.18};
const STARTING_CAPITAL=96453,FEE_RATE=.001,STATE_KEY="fbiCryptoBankV6",PIN_KEY="fbiCryptoBankPinV6",READ_KEY="fbiCryptoBankReadV6",MARKET_KEY="fbiCryptoBankMarketV6";
const $=s=>document.querySelector(s),esc=x=>String(x??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[m])),eur=n=>new Intl.NumberFormat("de-DE",{style:"currency",currency:"EUR",maximumFractionDigits:2}).format(Number(n)||0),num=n=>new Intl.NumberFormat("de-DE",{maximumFractionDigits:6}).format(Number(n)||0);
let market=[],marketMeta={status:"initializing",time:null,latency:null},syncing=false;
const defaultState=()=>({version:6,cash:STARTING_CAPITAL,positions:{},orders:[],ledger:[{date:new Date().toISOString(),journal:"Opening capital",debit:"Cash",credit:"Opening Equity",debitAmount:STARTING_CAPITAL,creditAmount:STARTING_CAPITAL,amount:STARTING_CAPITAL,ref:"OPEN-96453"}],opps:[{id:"OPP-001",asset:"Bitcoin",thesis:"Review liquidity, trend and volatility before allocation.",score:82,status:"WATCHLIST"}],audit:[{id:"AUD-0001",time:new Date().toISOString(),action:"SYSTEM",detail:"Research account initialized at €96,453.00",read:false}],realized:0,growth:{rate:.01,base:STARTING_CAPITAL,startedAt:new Date().toISOString()}});
function loadState(){try{const raw=localStorage.getItem(STATE_KEY);if(raw){const s=JSON.parse(raw);if(s&&s.version===6)return s}}catch{}return defaultState()}
let state=loadState();
function save(){localStorage.setItem(STATE_KEY,JSON.stringify(state))}
function ref(prefix="TX"){return `${prefix}-${Date.now().toString(36).toUpperCase()}-${Math.random().toString(36).slice(2,6).toUpperCase()}`}
function audit(action,detail){state.audit.unshift({id:ref("AUD"),time:new Date().toISOString(),action,detail,read:false});state.audit=state.audit.slice(0,200);save()}
function price(id){return Number(market.find(x=>x.id===id)?.current_price)||FALLBACK[id]||0}
function totalMarket(){return state.cash+Object.entries(state.positions).reduce((s,[id,p])=>s+p.units*price(id),0)}
function totalCost(){return state.cash+Object.values(state.positions).reduce((s,p)=>s+p.cost,0)}
function rows(){const nav=totalMarket();return ASSETS.map(a=>{const p=state.positions[a[0]]||{units:0,cost:0},pr=price(a[0]),value=p.units*pr,pnl=value-p.cost;return {a,p,pr,value,pnl,weight:nav?value/nav*100:0}})}
function formatPct(x){return `${x>=0?"+":""}${Number(x||0).toFixed(2)}%`}
function model(){const g=state.growth||{rate:.01,base:STARTING_CAPITAL,startedAt:new Date().toISOString()},base=Number(g.base)||STARTING_CAPITAL,rate=Number(g.rate)||.01,days=Math.max(0,Math.floor((Date.now()-new Date(g.startedAt).getTime())/86400000)),capital=base*Math.pow(1+rate,days);return {base,rate,days,capital,gain:capital-base}}
function ledgerTotals(){let debit=0,credit=0;for(const l of state.ledger){debit+=Number(l.debitAmount)||0;credit+=Number(l.creditAmount)||0}return {debit,credit,diff:debit-credit}}
function show(id){document.querySelectorAll(".view").forEach(v=>v.hidden=true);$("#"+id).hidden=false;document.querySelectorAll(".quick button").forEach(b=>b.classList.toggle("active",b.dataset.tab===id));window.scrollTo({top:0,behavior:"smooth"})}
function render(){
  const nav=totalMarket(),rs=rows(),cost=totalCost(),unreal=rs.reduce((s,x)=>s+x.pnl,0),g=model();
  $("#netWorth").textContent=eur(nav);$("#marketValue").textContent=eur(nav);$("#bookCost").textContent=eur(cost);$("#liquidity").textContent=eur(state.cash);$("#unrealized").textContent=eur(unreal);$("#realized").textContent=eur(state.realized);$("#txCount").textContent=state.orders.length;$("#auditCount").textContent=state.audit.length;
  $("#dailyPnl").innerHTML=`${formatPct(g.rate*100)} <span>modeled daily scenario</span>`;$("#growthBadge").textContent=`Scenario engine · ${(g.rate*100).toFixed(2)}% daily`;
  const btc=rs.find(x=>x.a[0]==="bitcoin");$("#btcValue").textContent=eur(btc.value);$("#btcUnits").textContent=`${btc.p.units.toFixed(6)} BTC`;$("#btcPnl").textContent=btc.p.cost?formatPct(btc.pnl/btc.p.cost*100):"0.00%";$("#btcPnl").className=btc.pnl>=0?"positive":"negative";$("#btcBar").style.width=Math.min(100,btc.weight*2)+"%";
  $("#portfolioRows").innerHTML=rs.map(x=>`<div class="portfolio-row"><div class="coin-icon">${x.a[1][0]}</div><div class="asset-name"><b>${x.a[2]}</b><small>${x.a[1]}</small></div><div class="value">${eur(x.value)}</div><div class="${x.pnl>=0?"positive":"negative"}" style="text-align:right;font-size:10px">${formatPct(x.p.cost?x.pnl/x.p.cost*100:0)}</div></div>`).join("");
  $("#positions").innerHTML=rs.filter(x=>x.p.units>0).map(x=>`<tr><td><b>${x.a[2]}</b> ${x.a[1]}</td><td>${num(x.p.units)}</td><td>${eur(x.p.cost)}</td><td>${eur(x.value)}</td><td class="${x.pnl>=0?"positive":"negative"}">${eur(x.pnl)}</td><td>${x.weight.toFixed(2)}%</td></tr>`).join("")||`<tr><td colspan="6">No positions yet.</td></tr>`;
  $("#tradeAsset").innerHTML=ASSETS.map(a=>`<option value="${a[0]}">${a[1]} — ${a[2]}</option>`).join("");
  $("#marketRows").innerHTML=rs.map(x=>{const m=market.find(y=>y.id===x.a[0]);return `<tr><td><b>${x.a[1]}</b> ${x.a[2]}</td><td>${eur(x.pr)}</td><td class="${(m?.price_change_percentage_24h||0)>=0?"positive":"negative"}">${m?.price_change_percentage_24h==null?"—":formatPct(m.price_change_percentage_24h)}</td><td>${eur(x.value)}</td><td>${x.weight.toFixed(2)}%</td></tr>`}).join("");
  $("#marketMode").textContent=marketMeta.status==="live-reference"?"Live reference":marketMeta.status==="fallback-reference"?"Reference fallback":"Local reference";$("#marketSource").textContent=marketMeta.status==="live-reference"?"CoinGecko":"Built-in reference";$("#marketLatency").textContent=marketMeta.latency==null?"—":`${marketMeta.latency} ms`;$("#marketLastGood").textContent=marketMeta.time?marketMeta.time.toLocaleTimeString():"—";
  renderAccounting(nav,cost,unreal);renderRisk(nav,rs);renderGrowth(g);renderOpps();renderAudit();renderNotifications();renderCurve();
}
function renderAccounting(nav,cost,unreal){const lt=ledgerTotals(),balanced=Math.abs(lt.diff)<.005;$("#ledgerStatus").textContent=balanced?"BALANCED":"CHECK REQUIRED";$("#bookStatus").textContent=balanced?"BOOK BALANCED":"CHECK REQUIRED";$("#ledgerRows").innerHTML=state.ledger.slice(0,80).map(l=>`<tr><td>${new Date(l.date).toLocaleString()}</td><td>${esc(l.journal)}</td><td>${esc(l.debit)}</td><td>${esc(l.credit)}</td><td>${eur(l.amount)}</td><td>${esc(l.ref)}</td></tr>`).join("")||`<tr><td colspan="6">No journal entries yet.</td></tr>`;$("#trialBalance").innerHTML=`<p><span>Total debits</span><b>${eur(lt.debit)}</b></p><p><span>Total credits</span><b>${eur(lt.credit)}</b></p><p><span>Difference</span><b class="${balanced?"positive":"negative"}">${eur(lt.diff)}</b></p><p><span>Journal status</span><b class="${balanced?"positive":"negative"}">${balanced?"RECONCILED":"REVIEW"}</b></p>`;$("#balanceSheet").innerHTML=`<p><span>Cash & liquidity</span><b>${eur(state.cash)}</b></p><p><span>Investment assets at cost</span><b>${eur(cost-state.cash)}</b></p><p><span>Unrealized revaluation</span><b>${eur(unreal)}</b></p><p><span>Total market assets</span><b>${eur(nav)}</b></p><p><span>Liabilities</span><b>€0.00</b></p><p><span>Market equity</span><b>${eur(nav)}</b></p>`;const fees=state.orders.reduce((s,o)=>s+o.fee,0);$("#incomeStatement").innerHTML=`<p><span>Realized P&L</span><b>${eur(state.realized)}</b></p><p><span>Unrealized P&L</span><b>${eur(unreal)}</b></p><p><span>Trading fees</span><b>${eur(fees)}</b></p><p><span>Net modeled P&L</span><b>${eur(state.realized+unreal-fees)}</b></p>`}
function renderRisk(nav,rs){const sorted=[...rs].sort((a,b)=>b.value-a.value),largest=sorted[0],conc=nav?largest.value/nav*100:0,liq=nav?state.cash/nav*100:0,turn=nav?state.orders.reduce((s,o)=>s+o.amount,0)/nav*100:0,score=Math.min(100,Math.round(conc*.65+(liq<10?25:liq<20?12:0)+(turn>100?15:0)));$("#riskScore").textContent=`${score} / 100`;$("#riskBar").style.width=score+"%";$("#concentration").textContent=conc.toFixed(1)+"%";$("#liquidityPct").textContent=liq.toFixed(1)+"%";$("#largest").textContent=largest?.a[1]||"—";$("#turnover").textContent=turn.toFixed(2)+"%";$("#riskPosture").textContent=score<35?"CONTROLLED":score<65?"WATCH":"HIGH ATTENTION";$("#stressRows").innerHTML=[-10,-25,-50].map(shock=>{const stressed=state.cash+(nav-state.cash)*(1+shock/100);return `<div class="stress"><span>${shock}% crypto shock</span><b>${eur(stressed)}</b></div>`}).join("")}
function renderGrowth(g){const s=Number($("#start")?.value||g.base),r=Number($("#rate")?.value||g.rate),d=Number($("#days")?.value||30),e=s*Math.pow(1+r,d);$("#projected").textContent=eur(e);$("#scenarioGain").textContent=eur(e-s);$("#multiple").textContent=(e/s).toFixed(2)+"×";$("#growthStatus").textContent=(g.rate*100).toFixed(2)+"%";$("#growthLive").textContent=`${eur(g.capital)} current scenario capital · ${g.days} day(s) elapsed`;const periods=[7,30,90,365];$("#projectionGrid").innerHTML=periods.map(days=>{const value=g.base*Math.pow(1+g.rate,days);return `<div><small>${days}D</small><b>${eur(value)}</b><span>${formatPct((Math.pow(1+g.rate,days)-1)*100)}</span></div>`}).join("")}
function renderOpps(){$("#oppList").innerHTML=state.opps.length?state.opps.map(o=>`<div class="opp"><div><b>${esc(o.asset)}</b><small>${esc(o.thesis)}</small></div><span class="score">${Number(o.score)||0}</span><span class="status">${esc(o.status)}</span></div>`).join(""):"<div class=muted>No opportunities in pipeline.</div>"}
function renderAudit(){$("#auditRows").innerHTML=state.audit.slice(0,20).map(x=>`<div class="audit"><b>${esc(x.action)}</b><small>${new Date(x.time).toLocaleString()} · ${esc(x.detail)} · ${esc(x.id)}</small></div>`).join("")}
function renderNotifications(){const unread=state.audit.filter(x=>!x.read).length;$("#notifCount").textContent=Math.min(99,unread);const recent=state.audit.slice(0,10);$("#notificationPanel").innerHTML=recent.length?recent.map(x=>`<div class="notif-item"><b>${esc(x.action)}</b><span>${esc(x.detail)}</span><small>${new Date(x.time).toLocaleString()}</small></div>`).join(""):"<div class=notif-empty>No recent events.</div>"}
function renderCurve(){const d=Number($("#period")?.value||30),g=model(),points=[];for(let i=0;i<16;i++){const t=i/15*d,v=g.base*Math.pow(1+g.rate,t),norm=Math.log(v/g.base)/Math.log(Math.max(1.000001,Math.pow(1+g.rate,d))),y=155-norm*125;points.push(`${i*(500/15)},${y.toFixed(1)}`)}$("#curve").setAttribute("points",points.join(" "));const ret=(Math.pow(1+g.rate,d)-1)*100;$("#periodReturn").textContent=formatPct(ret);$("#volatility").textContent=(g.rate*100*2.1).toFixed(2)+"% model";$("#drawdown").textContent="0.00% model"}
function setMarketState(status,time,latency){marketMeta={status,time,latency};const box=$("#syncBox"),dot=$("#syncDot");box.classList.remove("stale","error");dot.classList.remove("busy");$("#syncText").textContent="MARKET SYNC";$("#syncTime").textContent=time?`Updated ${time.toLocaleTimeString()}`:"Unavailable"}
function localReference(){return ASSETS.map(a=>({id:a[0],symbol:a[1].toLowerCase(),current_price:FALLBACK[a[0]],price_change_percentage_24h:null}))}
function saveMarketSnapshot(){try{localStorage.setItem(MARKET_KEY,JSON.stringify({savedAt:new Date().toISOString(),data:market}))}catch{}}
function loadMarketSnapshot(){try{const x=JSON.parse(localStorage.getItem(MARKET_KEY)||"null");if(x?.data?.length)return {data:x.data,time:new Date(x.savedAt)}}catch{}return null}
async function markets(){if(syncing)return;syncing=true;const started=performance.now(),box=$("#syncBox"),dot=$("#syncDot");$("#syncText").textContent="MARKET SYNC";$("#syncTime").textContent="Syncing…";$("#marketMode").textContent="Syncing";dot.classList.add("busy");$("#syncNow").disabled=true;
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),6500);
  try{const r=await fetch(`/api/market?ts=${Date.now()}`,{cache:"no-store",headers:{Accept:"application/json"},signal:controller.signal});clearTimeout(timer);const type=r.headers.get("content-type")||"";if(!r.ok||!type.toLowerCase().includes("application/json"))throw new Error(`endpoint ${r.status}`);const payload=await r.json();if(!payload?.ok||!Array.isArray(payload.data)||payload.data.length<5)throw new Error("invalid payload");market=payload.data;const t=new Date(payload.asOf||Date.now()),latency=Math.round(performance.now()-started);setMarketState(payload.mode||"fallback-reference",t,latency);saveMarketSnapshot();audit("MARKET SYNC",payload.mode==="live-reference"?"Live reference market refreshed":"Provider unavailable; fallback reference used");}
  catch(e){clearTimeout(timer);const snap=loadMarketSnapshot();if(snap){market=snap.data;setMarketState("fallback-reference",snap.time,Math.round(performance.now()-started));$("#syncTime").textContent=`Cached ${snap.time.toLocaleTimeString()}`;}else{market=localReference();setMarketState("local-reference",new Date(),Math.round(performance.now()-started));$("#syncTime").textContent="Local reference";}box.classList.add("stale");}
  finally{syncing=false;dot.classList.remove("busy");$("#syncNow").disabled=false;render();updateHealth();}}
function updateHealth(){const live=marketMeta.status==="live-reference";$("#healthSummary").textContent=live?`Market live · ${marketMeta.latency??"—"} ms · last update ${marketMeta.time?.toLocaleTimeString()||"—"}`:`Market ${marketMeta.status.replace("-"," ")} · dashboard operational`;$("#healthSummary").style.color=live?"#55d9a1":"#d6b76b"}
function postTrade(e){e.preventDefault();const action=$("#tradeAction").value,id=$("#tradeAsset").value,amount=Number($("#tradeAmount").value),note=$("#tradeNote").value.trim()||"Research entry",p=price(id),a=ASSETS.find(x=>x[0]===id),msg=$("#tradeMsg");msg.hidden=true;if(!Number.isFinite(amount)||amount<=0||p<=0){msg.hidden=false;msg.textContent="Enter a valid notional and wait for a market price.";return}const fee=amount*FEE_RATE,old=state.positions[id]||{units:0,cost:0},r=ref("TX");if(action==="BUY"){if(amount+fee>state.cash){msg.hidden=false;msg.textContent="Insufficient modeled liquidity.";return}const units=amount/p;state.cash-=amount+fee;state.positions[id]={units:old.units+units,cost:old.cost+amount};state.ledger.unshift({date:new Date().toISOString(),journal:"Investment purchase",debit:"Investment Asset",credit:"Cash",debitAmount:amount,creditAmount:amount,amount,ref:r});state.ledger.unshift({date:new Date().toISOString(),journal:"Trading fee",debit:"Trading Expense",credit:"Cash",debitAmount:fee,creditAmount:fee,amount:fee,ref:r});audit("TRADE",`BUY ${a[1]} ${eur(amount)} · ${note}`)}else{if(old.units<=0){msg.hidden=false;msg.textContent="No modeled position available to sell.";return}const units=Math.min(old.units,amount/p),proceeds=units*p,costBasis=old.cost*(units/old.units),realized=proceeds-costBasis-fee;state.cash+=proceeds-fee;state.positions[id]={units:old.units-units,cost:Math.max(0,old.cost-costBasis)};state.realized+=realized;state.ledger.unshift({date:new Date().toISOString(),journal:"Investment sale",debit:"Cash",credit:"Investment Asset",debitAmount:proceeds,creditAmount:costBasis,amount:proceeds,ref:r});if(realized>=0)state.ledger.unshift({date:new Date().toISOString(),journal:"Realized gain",debit:"",credit:"Realized Gain",debitAmount:0,creditAmount:realized,amount:realized,ref:r});else state.ledger.unshift({date:new Date().toISOString(),journal:"Realized loss",debit:"Realized Loss",credit:"",debitAmount:Math.abs(realized),creditAmount:0,amount:Math.abs(realized),ref:r});state.ledger.unshift({date:new Date().toISOString(),journal:"Trading fee",debit:"Trading Expense",credit:"Cash",debitAmount:fee,creditAmount:fee,amount:fee,ref:r});audit("TRADE",`SELL ${a[1]} ${eur(proceeds)} · ${note}`)}state.orders.unshift({ref:r,date:new Date().toISOString(),action,symbol:a[1],asset:id,amount,price:p,fee,note});state.orders=state.orders.slice(0,200);save();msg.hidden=false;msg.textContent=`${action} ${a[1]} recorded · Ref ${r}`;$("#tradeForm").reset();render()}
function exportCSV(){const header=["Ref","Date","Action","Asset","Notional EUR","Reference Price EUR","Fee EUR","Note"],lines=[header,...state.orders.map(o=>[o.ref,o.date,o.action,o.symbol,o.amount,o.price,o.fee,o.note])],csv=lines.map(r=>r.map(x=>`"${String(x??"").replaceAll('"','""')}"`).join(",")).join("\n");download(csv,"fbi-crypto-bank-transactions.csv","text/csv")}
function backup(){download(JSON.stringify({exportedAt:new Date().toISOString(),state,market,marketMeta},null,2),"fbi-crypto-bank-backup.json","application/json")}
function download(content,name,type){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function sha(v){const b=await crypto.subtle.digest("SHA-256",new TextEncoder().encode(v));return [...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,"0")).join("")}
async function pinHash(){let h=localStorage.getItem(PIN_KEY);if(!h){h=await sha("123456");localStorage.setItem(PIN_KEY,h)}return h}
async function unlock(pinValue){if(pinValue!==undefined&&await sha(pinValue)!==await pinHash())return false;$("#authScreen").classList.add("unlocked");sessionStorage.setItem("fbiAuth","1");return true}
function lock(){sessionStorage.removeItem("fbiAuth");$("#authScreen").classList.remove("unlocked");$("#loginPin").value=""}
async function init(){
  if(sessionStorage.getItem("fbiAuth")==="1")unlock();else{$("#authScreen").classList.remove("unlocked");await pinHash()}
  $("#loginForm").onsubmit=async e=>{e.preventDefault();if(await unlock($("#loginPin").value))$("#loginError").hidden=true;else $("#loginError").hidden=false};$("#lockBtn").onclick=lock;$("#profileBtn").onclick=()=>show("admin");document.querySelectorAll(".quick button").forEach(b=>b.onclick=()=>show(b.dataset.tab));
  $("#tradeForm").onsubmit=postTrade;$("#runGrowth").onclick=()=>{const rate=Number($("#rate").value),base=Number($("#start").value)||STARTING_CAPITAL;state.growth={rate,base,startedAt:new Date().toISOString()};audit("SCENARIO",`${(rate*100).toFixed(2)}% daily compounding model reset at ${eur(base)}`);save();render()};$("#rate").onchange=render;$("#days").oninput=render;$("#start").oninput=render;$("#period").onchange=renderCurve;
  $("#statementRefresh").onclick=render;$("#csvBtn").onclick=exportCSV;$("#jsonBtn").onclick=backup;$("#printBtn").onclick=()=>window.print();$("#readAll").onclick=()=>{state.audit.forEach(x=>x.read=true);save();renderNotifications()};$("#notifBtn").onclick=()=>$("#notificationPanel").classList.toggle("open");document.addEventListener("click",e=>{if(!e.target.closest(".notif-wrap"))$("#notificationPanel").classList.remove("open")});
  $("#syncNow").onclick=markets;$("#newOpp").onclick=()=>{const asset=prompt("Asset / investment:" );if(!asset)return;const thesis=prompt("Investment thesis:")||"Research pending";const score=Math.max(0,Math.min(100,Number(prompt("Opportunity score 0–100:")||50)));state.opps.unshift({id:ref("OPP"),asset,thesis,score,status:"WATCHLIST"});audit("OPPORTUNITY",`Added ${asset} to pipeline`);save();render()};
  $("#resetBtn").onclick=()=>{if(confirm("Reset all local research data and return to €96,453 starting capital?")){localStorage.removeItem(STATE_KEY);localStorage.removeItem(MARKET_KEY);location.reload()}};
  $("#pinForm").onsubmit=async e=>{e.preventDefault();const c=$("#currentPin").value,n=$("#newPin").value,k=$("#confirmPin").value,m=$("#pinMsg");m.hidden=false;if(await sha(c)!==await pinHash()){m.textContent="Current PIN is incorrect.";m.className="auth-message error";return}if(!/^\d{4,12}$/.test(n)||n!==k){m.textContent="Use a matching 4–12 digit PIN.";m.className="auth-message error";return}localStorage.setItem(PIN_KEY,await sha(n));m.textContent="PIN changed successfully.";m.className="auth-message success";e.target.reset();audit("SECURITY","PIN changed locally")};
  if("serviceWorker"in navigator)navigator.serviceWorker.ready.then(()=>$("#swStatus").textContent="Active").catch(()=>$("#swStatus").textContent="Unavailable");render();markets();setInterval(markets,60000)
}
init();
